#pragma once

#include <cstdint>
#include <string>
#include <vector>

/*
 * Shared perception types for detector / tracker / GUI / future ROS interfaces.
 */

struct Detection
{
    float x = 0.0f;
    float y = 0.0f;
    float w = 0.0f;
    float h = 0.0f;

    float confidence = 0.0f;
    int classId = -1;
    std::string label;
    bool valid = false;

    // Frame-level tracking/debug metadata.
    // This does NOT move the servo camera; it is only for stable detections in the video stream.
    int trackId = -1;
    int trackHits = 0;
    int trackAge = 0;
    bool trackStableBest = false;
    float currentConfidence = 0.0f;
    float bestConfidence = 0.0f;
    bool weak = false;
    std::string rejectReason;

    // Part C ROI second-pass metadata.
    // roiPass=true means this detection came from a second inference on a crop,
    // not directly from the full camera frame.
    bool roiPass = false;
    int roiGroupSize = 0;
    int roiSourceAcceptedCount = 0;
    int roiSourceWeakCount = 0;
    float roiPaddingRatio = 0.0f;
    std::string roiReason;

    // YOLOv8-seg mask/debug metadata.
    // mask is stored as a compact low-resolution binary mask, source-space low resolution, usually 320x180.
    // It is used for color filtering and optional GUI overlay.
    std::vector<std::uint8_t> mask;
    int maskWidth = 0;
    int maskHeight = 0;
    float maskArea = 0.0f;
    float boxArea = 0.0f;
    float maskDensity = 0.0f;
    float redRatio = 0.0f;
    float orangeRatio = 0.0f;
    float warmRatio = 0.0f;
    float greenYellowRatio = 0.0f;

    // Ver28 maturity competition / stable display metadata.
    // These fields allow the GUI/video/client to keep only one maturity label
    // for the same physical tomato or bunch, while keeping the losing candidate
    // in JSON for debugging.
    bool maturityCompetitionWinner = false;
    bool lostMaturityCompetition = false;
    bool displaySuppressed = false;
    bool classLocked = false;
    int switchCandidateFrames = 0;
    float maturityScore = 0.0f;
    float maturityScoreRipe = 0.0f;
    float maturityScoreUnripe = 0.0f;
    std::string maturityCompetitionReason;

    // Ver27 bunch/cluster support metadata.
    // A bunch can be promoted from weak to accepted if it is supported by
    // several strong single-tomato detections inside the same region.
    bool clusterPromoted = false;
    bool classCorrected = false;
    int originalClassId = -1;
    std::string originalLabel;
    std::string displaySource;
    std::string promotionReason;

    // Ver32 experimental runtime policy metadata.
    // These fields are additive and keep the old weak/valid/class_id contract for the GUI and Next.js.
    // sourceType is usually "model"; heuristic boxes generated by policy rules use "heuristic".
    std::string sourceType = "model";
    std::string policyStatus;      // strong / weak / noise / review / color_corrected / heuristic
    bool heuristic = false;
    std::string heuristicType;
    std::string anchorBunchClass;
    float anchorBunchConfidence = 0.0f;
    int childCount = 0;
    int weakChildCount = 0;
    int strongChildCount = 0;
    float weightedChildCount = 0.0f;
    float ripeEvidenceScore = 0.0f;
    float unripeEvidenceScore = 0.0f;
    std::string dominantMaturity;
    float heuristicScore = 0.0f;
    bool reviewCandidate = false;
    std::string reviewReason;
    bool colorCorrectedByPolicy = false;
    std::string correctionReason;
    float colorCorrectionScore = 0.0f;
    int supportMemberCount = 0;
    int supportRipeCount = 0;
    int supportUnripeCount = 0;
    float supportConfSum = 0.0f;
    float supportRipeConfSum = 0.0f;
    float supportUnripeConfSum = 0.0f;
    float bunchSupportScore = 0.0f;

    bool hasOriginalBbox = false;
    float originalX = 0.0f;
    float originalY = 0.0f;
    float originalW = 0.0f;
    float originalH = 0.0f;
    bool hasRefinedBbox = false;
    float refinedX = 0.0f;
    float refinedY = 0.0f;
    float refinedW = 0.0f;
    float refinedH = 0.0f;

    // Internal temporary YOLOv8-seg mask coefficients.
    // Cleared before detections are published to the GUI snapshot.
    std::vector<float> maskCoeffs;
};

struct Frame
{
    const std::uint8_t* data = nullptr;
    int width = 0;
    int height = 0;
    int channels = 3;
    int strideBytes = 0;
    std::uint64_t timestampMs = 0;
};

struct DetectionSnapshot
{
    Frame frame{};
    std::vector<std::uint8_t> frameBytes;
    std::vector<Detection> detections;

    // Raw model candidates after YOLO post-process/NMS but before project rules and tracking.
    // Used only for debug comparison against Python/Ultralytics.
    std::vector<Detection> rawCandidates;

    bool valid = false;

    bool isFresh = false;
    std::uint64_t timeoutMs = 500;
    std::uint64_t lastUpdateTimeMs = 0;
};

struct TrackingState
{
    bool trackingEnabled = false;
    bool targetSelected = false;

    float targetOffsetX = 0.0f;
    float targetOffsetY = 0.0f;

    float confidence = 0.0f;

    bool isFresh = false;
    std::uint64_t timeoutMs = 500;
    std::uint64_t lastUpdateTimeMs = 0;
};

